version: "1.0"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: quarkus-mssql
    environment:
      - ACCEPT_EULA=Y
      - HACK_PASSWORD=${HACK_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile.jvm 
    container_name: Simulador_Financiamento
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    volumes:
      - ./data/h2:/opt/app/data   # persiste o H2 em arquivo
    restart: unless-stopped
