version: "1.0"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: quarkus-mssql
    environment:
      - ACCEPT_EULA=Y
      - HACK_PASSWORD=${HACK_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile.jvm 
    container_name: Simulador_Financiamento
    env_file:
      - .env
      # environment:
      #   - quarkus.datasource.db-kind=h2
      #   - quarkus.datasource.jdbc.url=jdbc:h2:file:./data/testdb
      #   - quarkus.datasource.username=
      #   - quarkus.datasource.password=
      #   - quarkus.datasource.jdbc.driver=org.h2.Driver
      #   - quarkus.hibernate-orm.packages=org.caixa.Historico
      #   - quarkus.hibernate-orm.database.generation=drop-and-create
      #   - quarkus.swagger-ui.always-include=true
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    volumes:
      - ./data/h2:/opt/app/data   # persiste o H2 em arquivo
    restart: unless-stopped
